
import './globals.css'
import Sidebar from './sidebar/page'
import Navbar from './navbar/page'
import { Roboto } from "next/font/google";
import "tw-elements-react/dist/css/tw-elements-react.min.css";


const roboto =  Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="flex flex-wrap">
          <section className="hidden md:flex w-[20%] h-[100vh] overflow-y-scroll overflow-x-hidden">
            <Sidebar />
          </section>
          <section  className='w-[100%] md:w-[80%] h-[100vh] overflow-x-hidden overflow-y-scroll bg-[#f6f7fb]'>
            <div>
              <Navbar />
            </div>
            {children}
          </section>
        </main>
      </body>
    </html>
  )
}
